config/routes.rb
require 'sidekiq/web'
require 'api/api'

Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git.bin_path,
    project_root: Gitlab.config.gitlab_shell.repos_path,
    upload_pack:  Gitlab.config.gitlab_shell.upload_pack,
    receive_pack: Gitlab.config.gitlab_shell.receive_pack
  }), at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }

  #
  # Help
  #
  get 'help'                => 'help#index'
  get 'help/api'            => 'help#api'
  get 'help/api/:category'  => 'help#api', as: 'help_api_file'
  get 'help/markdown'       => 'help#markdown'
  get 'help/permissions'    => 'help#permissions'
  get 'help/public_access'  => 'help#public_access'
  get 'help/raketasks'      => 'help#raketasks'
  get 'help/ssh'            => 'help#ssh'
  get 'help/system_hooks'   => 'help#system_hooks'
  get 'help/web_hooks'      => 'help#web_hooks'
  get 'help/workflow'       => 'help#workflow'
  get 'help/shortcuts'

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get "raw"
    end
  end
  get "/s/:username" => "snippets#user_index", as: :user_snippets, constraints: { username: /.*/ }

  #
  # Public namespace
  #
  namespace :public do
    resources :projects, only: [:index]
    root to: "projects#index"
  end

  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :project_teams_update
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]

    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show] do
      resources :members, only: [:destroy]
    end

    root to: "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :account
      get :history
      get :token
      get :design

      put :update_password
      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create]
      resources :keys
      resources :groups, only: [:index] do
        member do
          delete :leave
        end
      end
    end
  end

  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }



  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard", only: [:show] do
    member do
      get :projects
      get :issues
      get :merge_requests
    end
  end

  #
  # Groups Area
  #
  resources :groups, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}  do
    member do
      get :issues
      get :merge_requests
      get :members
    end

    resources :users_groups, only: [:create, :update, :destroy]
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /(?:[a-zA-Z.0-9_\-]+\/)?[a-zA-Z.0-9_\-]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      put :transfer
      post :fork
      get :autocomplete_sources
    end

    scope module: :projects do
      resources :blob,    only: [:show], constraints: {id: /.+/}
      resources :raw,    only: [:show], constraints: {id: /.+/}
      resources :tree,    only: [:show], constraints: {id: /.+/, format: /(html|js)/ }
      resources :edit_tree,    only: [:show, :update], constraints: {id: /.+/}, path: 'edit'
      resources :commit,  only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
      resources :commits, only: [:show], constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}
      resources :compare, only: [:index, :create]
      resources :blame,   only: [:show], constraints: {id: /.+/}
      resources :network,   only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
      resources :graphs, only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
      match "/compare/:from...:to" => "compare#show", as: "compare", via: [:get, :post], constraints: {from: /.+/, to: /.+/}

        resources :snippets do
          member do
            get "raw"
          end
        end

      resources :wikis, only: [:show, :edit, :destroy, :create] do
        collection do
          get :pages
          put ':id' => 'wikis#update'
          get :git_access
        end

        member do
          get "history"
        end
      end

      resource :wall, only: [:show] do
        member do
          get 'notes'
        end
      end

      resource :repository, only: [:show] do
        member do
          get "stats"
          get "archive"
        end
      end

      resources :services, constraints: { id: /[^\/]+/ }, only: [:index, :edit, :update] do
        member do
          get :test
        end
      end

      resources :deploy_keys do
        member do
          put :enable
          put :disable
        end
      end

      resources :tags, only: [:index, :new, :create, :destroy]
      resources :branches, only: [:index, :new, :create, :destroy]
      resources :protected_branches, only: [:index, :create, :destroy]

      resources :refs, only: [] do
        collection do
          get "switch"
        end

        member do
          # tree viewer logs
          get "logs_tree", constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ }
          get "logs_tree/:path" => "refs#logs_tree",
            as: :logs_file,
            constraints: {
              id:   /[a-zA-Z.0-9\/_\-#%+]+/,
              path: /.*/
            }
        end
      end

      resources :merge_requests, constraints: {id: /\d+/}, except: [:destroy] do
        member do
          get :diffs
          get :automerge
          get :automerge_check
          get :ci_status
        end

        collection do
          get :branch_from
          get :branch_to
        end
      end

      resources :hooks, only: [:index, :create, :destroy] do
        member do
          get :test
        end
      end

      resources :team, controller: 'team_members', only: [:index]
      resources :milestones, except: [:destroy]

      resources :labels, only: [:index] do
        collection do
          post :generate
        end
      end

      resources :issues, except: [:destroy] do
        collection do
          post  :bulk_update
        end
      end

      resources :team_members, except: [:index, :edit] do
        collection do

          # Used for import team
          # from another project
          get :import
          post :apply_import
        end
      end

      resources :notes, only: [:index, :create, :destroy, :update] do
        member do
          delete :delete_attachment
        end

        collection do
          post :preview
        end
      end
    end
  end

  root to: "dashboard#projects"
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  path                   :string(255)
#  description            :text
#  created_at             :datetime
#  updated_at             :datetime
#  creator_id             :integer
#  default_branch         :string(255)
#  issues_enabled         :boolean          default(TRUE), not null
#  wall_enabled           :boolean          default(TRUE), not null
#  merge_requests_enabled :boolean          default(TRUE), not null
#  wiki_enabled           :boolean          default(TRUE), not null
#  namespace_id           :integer
#  public                 :boolean          default(FALSE), not null
#  issues_tracker         :string(255)      default("gitlab"), not null
#  issues_tracker_id      :string(255)
#  snippets_enabled       :boolean          default(TRUE), not null
#  last_activity_at       :datetime
#  imported               :boolean          default(FALSE), not null
#

require "grit"

class Project < ActiveRecord::Base
  include Gitlab::ShellAdapter
  extend Enumerize

  attr_accessible :name, :path, :description, :default_branch, :issues_tracker, :label_list,
    :issues_enabled, :wall_enabled, :merge_requests_enabled, :snippets_enabled, :issues_tracker_id,
    :wiki_enabled, :public, :import_url, :last_activity_at, as: [:default, :admin]

  attr_accessible :namespace_id, :creator_id, as: :admin

  acts_as_taggable_on :labels, :issues_default_labels

  attr_accessor :import_url

  # Relations
  belongs_to :creator,      foreign_key: "creator_id", class_name: "User"
  belongs_to :group,        foreign_key: "namespace_id", conditions: "type = 'Group'"
  belongs_to :namespace

  has_one :last_event, class_name: 'Event', order: 'events.created_at DESC', foreign_key: 'project_id'
  has_one :gitlab_ci_service, dependent: :destroy
  has_one :campfire_service, dependent: :destroy
  has_one :hipchat_service, dependent: :destroy
  has_one :forked_project_link, dependent: :destroy, foreign_key: "forked_to_project_id"
  has_one :forked_from_project, through: :forked_project_link

  has_many :services,           dependent: :destroy
  has_many :events,             dependent: :destroy
  has_many :merge_requests,     dependent: :destroy
  has_many :issues,             dependent: :destroy, order: "state DESC, created_at DESC"
  has_many :milestones,         dependent: :destroy
  has_many :notes,              dependent: :destroy
  has_many :snippets,           dependent: :destroy, class_name: "ProjectSnippet"
  has_many :hooks,              dependent: :destroy, class_name: "ProjectHook"
  has_many :protected_branches, dependent: :destroy

  has_many :users_projects, dependent: :destroy
  has_many :users, through: :users_projects

  has_many :deploy_keys_projects, dependent: :destroy
  has_many :deploy_keys, through: :deploy_keys_projects

  delegate :name, to: :owner, allow_nil: true, prefix: true
  delegate :members, to: :team, prefix: true

  # Validations
  validates :creator, presence: true
  validates :description, length: { within: 0..2000 }
  validates :name, presence: true, length: { within: 0..255 },
            format: { with: Gitlab::Regex.project_name_regex,
                      message: "only letters, digits, spaces & '_' '-' '.' allowed. Letter should be first" }
  validates :path, presence: true, length: { within: 0..255 },
            exclusion: { in: Gitlab::Blacklist.path },
            format: { with: Gitlab::Regex.path_regex,
                      message: "only letters, digits & '_' '-' '.' allowed. Letter should be first" }
  validates :issues_enabled, :wall_enabled, :merge_requests_enabled,
            :wiki_enabled, inclusion: { in: [true, false] }
  validates :issues_tracker_id, length: { within: 0..255 }

  validates_uniqueness_of :name, scope: :namespace_id
  validates_uniqueness_of :path, scope: :namespace_id

  validates :import_url,
    format: { with: URI::regexp(%w(git http https)), message: "should be a valid url" },
    if: :import?

  validate :check_limit

  # Scopes
  scope :without_user, ->(user)  { where("projects.id NOT IN (:ids)", ids: user.authorized_projects.map(&:id) ) }
  scope :without_team, ->(team) { team.projects.present? ? where("projects.id NOT IN (:ids)", ids: team.projects.map(&:id)) : scoped  }
  scope :not_in_group, ->(group) { where("projects.id NOT IN (:ids)", ids: group.project_ids ) }
  scope :in_team, ->(team) { where("projects.id IN (:ids)", ids: team.projects.map(&:id)) }
  scope :in_namespace, ->(namespace) { where(namespace_id: namespace.id) }
  scope :in_group_namespace, -> { joins(:group) }
  scope :sorted_by_activity, -> { reorder("projects.last_activity_at DESC") }
  scope :personal, ->(user) { where(namespace_id: user.namespace_id) }
  scope :joined, ->(user) { where("namespace_id != ?", user.namespace_id) }
  scope :public_only, -> { where(public: true) }

  enumerize :issues_tracker, in: (Gitlab.config.issues_tracker.keys).append(:gitlab), default: :gitlab

  class << self
    def abandoned
      where('projects.last_activity_at < ?', 6.months.ago)
    end

    def with_push
      includes(:events).where('events.action = ?', Event::PUSHED)
    end

    def active
      joins(:issues, :notes, :merge_requests).order("issues.created_at, notes.created_at, merge_requests.created_at DESC")
    end

    def search query
      where("projects.name LIKE :query OR projects.path LIKE :query", query: "%#{query}%")
    end

    def find_with_namespace(id)
      if id.include?("/")
        id = id.split("/")
        namespace = Namespace.find_by_path(id.first)
        return nil unless namespace

        where(namespace_id: namespace.id).find_by_path(id.second)
      else
        where(path: id, namespace_id: nil).last
      end
    end

    def access_options
      UsersProject.access_roles
    end
  end

  def team
    @team ||= ProjectTeam.new(self)
  end

  def repository
    @repository ||= Repository.new(path_with_namespace, default_branch)
  end

  def saved?
    id && persisted?
  end

  def import?
    import_url.present?
  end

  def check_limit
    unless creator.can_create_project?
      errors[:limit_reached] << ("Your own projects limit is #{creator.projects_limit}! Please contact administrator to increase it")
    end
  rescue
    errors[:base] << ("Can't check your ability to create project")
  end

  def to_param
    if namespace
      namespace.path + "/" + path
    else
      path
    end
  end

  def web_url
    [Gitlab.config.gitlab.url, path_with_namespace].join("/")
  end

  def build_commit_note(commit)
    notes.new(commit_id: commit.id, noteable_type: "Commit")
  end

  def last_activity
    last_event
  end

  def last_activity_date
    last_activity_at || updated_at
  end

  def project_id
    self.id
  end

  def issues_labels
    @issues_labels ||= (issues_default_labels + issues.tags_on(:labels)).uniq.sort_by(&:name)
  end

  def issue_exists?(issue_id)
    if used_default_issues_tracker?
      self.issues.where(id: issue_id).first.present?
    else
      true
    end
  end

  def used_default_issues_tracker?
    self.issues_tracker == Project.issues_tracker.default_value
  end

  def can_have_issues_tracker_id?
    self.issues_enabled && !self.used_default_issues_tracker?
  end

  def build_missing_services
    available_services_names.each do |service_name|
      service = services.find { |service| service.to_param == service_name }

      # If service is available but missing in db
      # we should create an instance. Ex `create_gitlab_ci_service`
      service = self.send :"create_#{service_name}_service" if service.nil?
    end
  end

  def available_services_names
    %w(gitlab_ci campfire hipchat)
  end

  def gitlab_ci?
    gitlab_ci_service && gitlab_ci_service.active
  end

  # For compatibility with old code
  def code
    path
  end

  def items_for entity
    case entity
    when 'issue' then
      issues
    when 'merge_request' then
      merge_requests
    end
  end

  def send_move_instructions
    team.members.each do |user|
      Notify.delay.project_was_moved_email(self.id, user.id)
    end
  end

  def owner
    if namespace
      namespace_owner
    else
      creator
    end
  end

  def team_member_by_name_or_email(name = nil, email = nil)
    user = users.where("name like ? or email like ?", name, email).first
    users_projects.where(user: user) if user
  end

  # Get Team Member record by user id
  def team_member_by_id(user_id)
    users_projects.find_by_user_id(user_id)
  end

  def name_with_namespace
    @name_with_namespace ||= begin
                               if namespace
                                 namespace.human_name + " / " + name
                               else
                                 name
                               end
                             end
  end

  def namespace_owner
    namespace.try(:owner)
  end

  def path_with_namespace
    if namespace
      namespace.path + '/' + path
    else
      path
    end
  end

  def transfer(new_namespace)
    ProjectTransferService.new.transfer(self, new_namespace)
  end

  def execute_hooks(data)
    hooks.each { |hook| hook.async_execute(data) }
  end

  def execute_services(data)
    services.each do |service|

      # Call service hook only if it is active
      service.execute(data) if service.active
    end
  end

  def discover_default_branch
    # Discover the default branch, but only if it hasn't already been set to
    # something else
    if repository && default_branch.nil?
      update_attributes(default_branch: self.repository.discover_default_branch)
    end
  end

  def update_merge_requests(oldrev, newrev, ref, user)
    return true unless ref =~ /heads/
    branch_name = ref.gsub("refs/heads/", "")
    c_ids = self.repository.commits_between(oldrev, newrev).map(&:id)

    # Update code for merge requests

app/views/groups/_filter.html.haml
= form_tag group_filter_path(entity), method: 'get' do
  %fieldset
    %ul.nav.nav-pills.nav-stacked
      %li{class: ("active" if !params[:status])}
        = link_to group_filter_path(entity, status: nil) do
          Open
      %li{class: ("active" if params[:status] == 'closed')}
        = link_to group_filter_path(entity, status: 'closed') do
          Closed
      %li{class: ("active" if params[:status] == 'all')}
        = link_to group_filter_path(entity, status: 'all') do
          All

  %fieldset
    %legend Projects:
    %ul.nav.nav-pills.nav-stacked
      - @projects.each do |project|
        - unless entities_per_project(project, entity).zero?
          %li{class: ("active" if params[:project_id] == project.id.to_s)}
            = link_to group_filter_path(entity, project_id: project.id) do
              = project.name_with_namespace
              %small.pull-right= entities_per_project(project, entity)
      - if @projects.blank?
        %p.nothing_here_message This group has no projects yet

  %fieldset
    %hr
    = link_to "Reset", group_filter_path(entity), class: 'btn pull-right'

app/views/groups/_new_group_member.html.haml
= form_for @users_group, url: group_users_groups_path(@group) do |f|
  %fieldset
    %legend= "New Group member(s) for #{@group.name}"

    %h6 1. Choose users you want in the group
    .clearfix
      = f.label :user_ids, "People"
      .input= users_select_tag(:user_ids, multiple: true, class: 'input-large')

    %h6 2. Set access level for them
    .clearfix
      = f.label :group_access, "Group Access"
      .input= select_tag :group_access, options_for_select(UsersGroup.group_access_roles, @users_group.group_access), class: "project-access-select chosen"

    .form-actions
      = f.submit 'Add users into group', class: "btn btn-create"

app/views/groups/_projects.html.haml
.ui-box
  .title
    Projects (#{projects.count})
    - if can? current_user, :manage_group, @group
      %span.pull-right
        = link_to new_project_path(namespace_id: @group.id), class: "btn" do
          %i.icon-plus
          New Project
  %ul.well-list
    - if projects.blank?
      %p.nothing_here_message This groups has no projects yet
    - projects.each do |project|
      %li.project-row
        = link_to project_path(project), class: dom_class(project) do
          %span.project-name
            = truncate(project.name, length: 25)
          %span.arrow
            %i.icon-angle-right
          %span.last-activity
            %span Last activity:
            %span.date= project_last_activity(project)

app/views/groups/edit.html.haml
.row
  .span2
    %ul.nav.nav-pills.nav-stacked.nav-stacked-menu
      %li.active
        = link_to '#tab-edit', 'data-toggle' => 'tab' do
          %i.icon-edit
          Edit Group
      %li
        = link_to '#tab-projects', 'data-toggle' => 'tab' do
          %i.icon-folder-close
          Projects
      %li
        = link_to 'Transfer', '#tab-transfer', 'data-toggle' => 'tab'
      %li
        = link_to 'Remove', '#tab-remove', 'data-toggle' => 'tab'

  .span10
    .tab-content
      .tab-pane.active#tab-edit
        .ui-box
          .title
            %strong= @group.name
            Group Settings:
          %div.form-holder
            = form_for @group do |f|
              - if @group.errors.any?
                .alert.alert-error
                  %span= @group.errors.full_messages.first
              .clearfix
                = f.label :name do
                  Group name is
                .input
                  = f.text_field :name, placeholder: "Ex. OpenSource", class: "xxlarge left"

              .clearfix.group-description-holder
                = f.label :description, "Details"
                .input
                  = f.text_area :description, maxlength: 250, class: "xxlarge js-gfm-input", rows: 4

              .form-actions
                = f.submit 'Save group', class: "btn btn-save"

      .tab-pane#tab-projects
        .ui-box
          .title
            %strong= @group.name
            Projects:
            - if can? current_user, :manage_group, @group
              %span.pull-right
                = link_to new_project_path(namespace_id: @group.id), class: "btn btn-tiny" do
                  %i.icon-plus
                  New Project
          %ul.well-list
            - @group.projects.each do |project|
              %li
                - if project.public
                  = public_icon
                - else
                  = private_icon
                = link_to project.name_with_namespace, project
                .pull-right
                  = link_to 'Team', project_team_index_path(project), id: "edit_#{dom_id(project)}", class: "btn btn-small"
                  = link_to 'Edit', edit_project_path(project), id: "edit_#{dom_id(project)}", class: "btn btn-small"
                  = link_to 'Remove', project, confirm: remove_project_message(project), method: :delete, class: "btn btn-small btn-remove"
            - if @group.projects.blank?
              %p.nothing_here_message This group has no projects yet

      .tab-pane#tab-transfer
        .ui-box.ui-box-danger
          .title Transfer group
          .ui-box-body
            %p
              Transferring group will cause loss of admin control over group and all child projects
            = form_for @group do |f|
              = users_select_tag(:'group[owner_id]')
              %hr
              = f.submit 'Transfer group', class: "btn btn-small btn-remove"

      .tab-pane#tab-remove
        .ui-box.ui-box-danger
          .title Remove group
          .ui-box-body
            %p
              Remove of group will cause removing all child projects and resources.
            %p
              %strong Removed group can not be restored!

            = link_to 'Remove Group', @group, confirm: 'Removed group can not be restored! Are you sure?', method: :delete, class: "btn btn-remove btn-small"

app/views/groups/issues.html.haml
%h3.page-title
  Issues
  %small (assigned to you)
  %small.pull-right #{@issues.total_count} issues

%hr
.row
  .span3
    = render 'filter', entity: 'issue'
  .span9
    - if @issues.any?
      - @issues.group_by(&:project).each do |group|
        %div.ui-box
          - project = group[0]
          .title
            = link_to_project project
          %ul.well-list.issues-list
            - group[1].each do |issue|
              = render 'projects/issues/issue', issue: issue
      %hr
      = paginate @issues, theme: "gitlab"
    - else
      %p.nothing_here_message Nothing to show here

app/views/groups/members.html.haml
- can_manage_group =  current_user.can? :manage_group, @group
.row
  .span6
    - if can_manage_group
      = render "new_group_member"
    - else
      .light-well
        %h4.nothing_here_message
          Only group owners can manage group members
  .span6
    .ui-box
      .title
        %strong #{@group.name}
        Group Members
        %small
          (#{@members.count})
      %ul.well-list
        - @members.each do |member|
          = render 'users_groups/users_group', member: member, show_controls: can_manage_group
    %p.light
      Group members get access to all projects in this group

app/views/groups/merge_requests.html.haml
%h3.page-title
  Merge Requests
  %small (authored by or assigned to you)
  %small.pull-right #{@merge_requests.total_count} merge requests

%hr
.row
  .span3
    = render 'filter', entity: 'merge_request'
  .span9
    = render 'shared/merge_requests'

app/views/groups/new.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    .alert.alert-error
      %span= @group.errors.full_messages.first
  .clearfix
    = f.label :name do
      Group name is
    .input
      = f.text_field :name, placeholder: "Ex. OpenSource", class: "xxlarge left"

  .clearfix.group-description-holder
    = f.label :description, "Details"
    .input
      = f.text_area :description, maxlength: 250, class: "xxlarge js-gfm-input", rows: 4

  .clearfix
    .input
      %ul
        %li Group is kind of directory for several projects
        %li All created groups are private
        %li People within a group see only projects they have access to
        %li All projects of group will be stored in a group directory
        %li You will be able to move existing projects into group

  .form-actions
    = f.submit 'Create group', class: "btn btn-create"

app/views/groups/show.html.haml
.dashboard
  .activities.span8
    = render "events/event_last_push", event: @last_push
    = link_to dashboard_path, class: 'btn btn-tiny' do
      &larr; To dashboard
    &nbsp;
    %span.cgray You will only see events from projects in this group
    %hr
    - if @events.any?
      .content_list
    - else
      %p.nothing_here_message Project activity will be displayed here
    .loading.hide
  .side.span4
    - if @group.description.present?
      .description-block
        = @group.description
    = render "projects", projects: @projects
    .prepend-top-20
      = link_to group_path(@group, { format: :atom, private_token: current_user.private_token }), title: "Feed" do
        %strong
          %i.icon-rss
          News Feed

    %hr
    = render 'shared/promo'

app/views/groups/show.js.haml
:plain 
  Pager.append(#{@events.count}, "#{escape_javascript(render(@events))}");